# brew tap Homebrew/brewdler

tap 'caskroom/cask'

brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'bash'
brew 'boot2docker'
brew 'chromedriver'
brew 'cmake'
brew 'ctags'
brew 'curl'
brew 'direnv'
brew 'git'
brew 'gnupg'
brew 'go'
brew 'go-app-engine-64'
brew 'heroku-toolbelt'
brew 'imagemagick'
brew 'liquidprompt'
brew 'mercurial'
brew 'mongodb'
brew 'mysql'
brew 'nvm'
brew 'phantomjs'
brew 'postgresql'
brew 'rbenv'
brew 'redis'
brew 'ruby-build'
brew 'tree'
brew 'vim'
brew 'zsh'

cask 'google-cloud-sdk'
