install apple-gcc42
install autoconf
install automake
install curl
install git
install gnupg
install imagemagick
install node
install openssl
install phantomjs
install direnv
install liquidprompt
install rbenv
install ruby-build
