#!/bin/bash

# Colorized listings
export CLICOLOR=1

# Colorized grep
export GREP_OPTIONS='--color=auto'

# Make libraries in /usr/local available to Python
export LD_RUN_PATH=/usr/local/lib

# Aliases
alias vi="vim"
alias a="atom"
alias c="code"
alias gsup="git submodule foreach git checkout master"
alias vup="vagrant up && vagrant ssh"
alias vsh="vagrant ssh"
alias vex="vagrant suspend &; exit"
alias dk="docker"
alias dkm="docker-machine"
alias dkms='docker-machine start && eval $(docker-machine env)'
alias dkc="docker-compose"
alias crl="/usr/local/Cellar/curl/7.47.0/bin/curl"
alias ossl="/usr/local/Cellar/openssl/1.0.2f/bin/openssl"

# Java
if [ -f /usr/libexec/java_home ]; then
	JAVA_HOME=$(/usr/libexec/java_home)
	export JAVA_HOME
else
	export JAVA_HOME=/usr/lib/jvm/default-java
fi

# Go
if [ -f $HOME/go/bin/go ]; then
 export PATH=$PATH:$HOME/go/bin
fi
export GOPATH=$HOME/GDrive/go_projects
export PATH=$PATH:$GOPATH/bin
GOROOT=$(go env GOROOT)
export GOROOT
export PATH=$PATH:$GOROOT/bin

# Rust
# if [ -d $HOME/.cargo/bin ]; then
#  export PATH=$PATH:$HOME/.cargo/bin
# fi
# if [ -d $HOME/GDrive/rust_projects/rust/src ]; then
#  export RUST_SRC_PATH=$HOME/GDrive/rust_projects/rust/src
# fi
if [ -d $HOME/.cargo/bin ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi
export RUST_SRC_PATH=$HOME/.multirust/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src

# Node
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR=$HOME/.editor
fi
export BUNDLER_EDITOR=$EDITOR
export GURNEL_EDITOR=$HOME/.gurnel_editor

# gpg-agent
GPG_TTY=$(tty)
export GPG_TTY
# shellcheck source=/home/mike/.gpg-agent-info
[ -f ~/.gpg-agent-info ] && source ~/.gpg-agent-info
if [ -S "${GPG_AGENT_INFO%%:*}" ]; then
  export GPG_AGENT_INFO
else
  eval "$(gpg-agent --daemon --write-env-file ~/.gpg-agent-info --default-cache-ttl 172800 --max-cache-ttl 1209600)"
fi

# modern terminals only
export TERM="xterm-256color"
